app: fullstack-app
component: aws-iam-role
name: permissions
inputs:
  name: '${name}-${stage}'
  region: us-east-1
  service: lambda.amazonaws.com
  policy:
    - Effect: Allow
      Action:
        - 'sts:AssumeRole'
        - 'logs:CreateLogGroup'
        - 'logs:CreateLogStream'
        - 'logs:PutLogEvents'
      Resource: '*'
    - Effect: Allow
      Action:
        - 'dynamodb:DescribeTable'
        - 'dynamodb:Query'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource:
        - '${output:database.arn}'
        - '${output:database.arn}/index/*'
        - 'arn:aws:dynamodb:us-east-1:552115164637:table/userSpending-dev'
    # - Effect: Allow
    #   Action:
    #     - 'dynamodb:DescribeTable'
    #     - 'dynamodb:Query'
    #     - 'dynamodb:GetItem'
    #     - 'dynamodb:PutItem'
    #     - 'dynamodb:UpdateItem'
    #     - 'dynamodb:DeleteItem'
    #   Resource:
    #     - 'arn:aws:dynamodb:us-east-1:552115164637:table/userSpending-dev'
        
